<?php

class Config {

   /*
    * Default settings - DO NOT EDIT!
    *
    * These can be overwritten in the configuration file "yafu2.conf".
    */

    public $Core = array(
            'Title' => "Yet Another File Upload <small>2.0</small>",
            'FilePool' => 'files/',
            'MaxFilesize' => 10000000,
            'MagicFile' => '/usr/share/misc/magic',
            'DebugInfo' => false,
            'TempFilePrefix' => 'auto',
            'SiPrefixes' => true,
    );

    public $Language = array(
            'AutoDetect' => true,
            'Default' => 'de',
            'LanguageDir' => 'i18n/',
    );

    public $Template = array(
            'TemplateDir' => 'html/',
            'CacheDir' => '.cache/',
            'OpenTag' => '<!--[',
            'CloseTag' => ']-->',
            'UseCaching' => true,
            'ImagePath' => 'images/',
    );

    /* End of default settings */

    public function Config($filepath) {
        if(file_exists($filepath)) {
            $tmpArray = parse_ini_file($this->ConfigFilePath($filepath), true);
            if(!$tmpArray) {
                die("Error parsing configuration file!");
            }
            foreach($tmpArray as $variable => $value) {
                if(is_array($value) && isset($this->$variable)) {
                    $this->$variable = array_merge($this->$variable, $value);
                } else {
                    $this->$variable = $value;
                }
            }
        } else {
            if(touch($filepath)) {
                $this->ConfigFilePath($filepath);
                $this->saveChanges(true);
            } else {
                die("Failed to create default configuration file!");
            }
        }

    }

    protected function ConfigFilePath($path = null) {
        static $configFile = null;

        $configFile = is_string($path) ? realpath($path) : $configFile;
        return $configFile;
    }

    public function saveChanges($change = null) {
        static $hasChanged = null;

        $hasChanged = is_bool($change) ? $change : $hasChanged;
        return (boolean) $hasChanged;
    }

    public function __destruct() {
        $unassignedItems = $assignedItems = array();
        foreach($this as $variable => $value) {
            if(is_scalar($value)) {
                $unassignedItems[$variable] = $value;
            } else {
                $assignedItems[$variable] = $value;
            }
        }
        $allItems = array_merge($unassignedItems, $assignedItems);

        if($this->saveChanges()) {
            write_ini_file(
                $this->ConfigFilePath(),
                $allItems,
                true,
                "This file was generated by yafu2. See help files for more informations."
            );
        }
    }

}

?>
